<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="TYSS-Lakshmi" failures="3" tests="3" name="TestRunner-1" time="84.01" errors="0" timestamp="2024-06-20T17:50:31 IST">
  <testcase classname="com.vTiger.crm.testNgTest.TC005_CreateLeadTest" name="createLead" time="10.225">
    <failure type="java.lang.AssertionError" message="expected [Leads] but found [Home]">
      <![CDATA[java.lang.AssertionError: expected [Leads] but found [Home]
at com.vTiger.crm.testNgTest.TC005_CreateLeadTest.createLead(TC005_CreateLeadTest.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- createLead -->
  <testcase classname="com.vTiger.crm.testNgTest.TC006_CreateLead_After_DeleteLeadTest" name="createLead_and_Delete" time="6.923">
    <failure type="java.lang.AssertionError" message="expected [Leads] but found [Home]">
      <![CDATA[java.lang.AssertionError: expected [Leads] but found [Home]
at com.vTiger.crm.testNgTest.TC006_CreateLead_After_DeleteLeadTest.createLead_and_Delete(TC006_CreateLead_After_DeleteLeadTest.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- createLead_and_Delete -->
  <testcase classname="com.vTiger.crm.testNgTest.TC007_CreateOpportunityTest" name="createOpportunity" time="6.45">
    <failure type="java.lang.AssertionError" message="expected [Contacts] but found [Home]">
      <![CDATA[java.lang.AssertionError: expected [Contacts] but found [Home]
at com.vTiger.crm.testNgTest.TC007_CreateOpportunityTest.createOpportunity(TC007_CreateOpportunityTest.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- createOpportunity -->
  <testcase classname="baseClassTestng.BaseClassTestNg" name="@BeforeSuite BeforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite BeforeSuite -->
  <testcase classname="baseClassTestng.BaseClassTestNg" name="@AfterSuite AfterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite AfterSuite -->
  <testcase classname="baseClassTestng.BaseClassTestNg" name="@BeforeSuite BeforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite BeforeSuite -->
  <testcase classname="baseClassTestng.BaseClassTestNg" name="@AfterSuite AfterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite AfterSuite -->
</testsuite> <!-- TestRunner-1 -->
